---
name: CI

'on':
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test on ${{ matrix.label }}
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - label: Debian (8)
            image: debian:jessie
            type: debian

          - label: Debian (9)
            image: debian:stretch
            type: debian

          # - label: Debian (10)
          #   image: debian:buster
          #   type: debian

          # - label: Ubuntu (16.04 LTS)
          #   image: ubuntu:xenial
          #   type: debian

          # - label: Ubuntu (18.04 LTS)
          #   image: ubuntu:bionic
          #   type: debian

          # - label: Ubuntu (20.04 LTS)
          #   image: ubuntu:focal
          #   type: debian

          # - label: CentOS (7)
          #   image: centos:7
          #   type: redhat
          
          # - label: CentOS (8)
          #   image: centos:8
          #   type: redhat

    steps:
      - uses: actions/checkout@v2
      - name: Configure environment
        run: |
          cp .github/docker/Dockerfile-${{ matrix.type }} Dockerfile
          sed -i 's/@@IMAGE@@/${{ matrix.image }}/g' Dockerfile

      - name: Run installer script
        uses: ./
        with:
          entrypoint: /entrypoint-local.sh

      - name: Run installer script (headless)
        uses: ./
        with:
          entrypoint: /entrypoint-remote.sh
